### PR TITLE
Added C++ code for Longest Increasing Path

### PR DESCRIPTION
**Pull request by arihantthriwe**
Hi i have added the solution for the above mentioned problem.
Please Check :)

### CODE REVIEW

**Comment by arihantthriwe** [comment]
I have also correctly modified the .gitignore file to contain .DS_Store files and deleted the Java/.DS_Store file.
Thank in advance 🙏

**Review by hanshulll — CHANGES_REQUESTED** [review]
@arihantthriwe 
**If like me you are on macOS and using git then use "rm -rf .DS_Store" command and remove it and I will merge your PR soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by arihantthriwe** [comment]
Done.
Please check @hanshulll :)

**Comment by hanshulll** [comment]
@arihantthriwe 
**Wohoo!! Congrarts🥳 your PR has been merged.**

**Comment by arihantthriwe** [comment]
🥳

**Pull request merged**
