### PR TITLE
Added Stack and Queue implementation in C#

### PR DESCRIPTION
**Pull request by SravanSTG**
Added stack and queue implementation in C#

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@SravanSTG 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by hanshulll** [comment]
@SravanSTG 
**Wohoo!! Congrats🥳 your PR has been merged.**

**Comment by hanshulll** [comment]
@SravanSTG 
**Thank you so much for your contribution and if possible do provide a detailed description of what type of contribution you've done**

**Comment by SravanSTG** [comment]
Thank you for merging. I implemented stack and queue in C#.

### Stack-

```
stack.Push(3);
stack.Push(8);
stack.Push(5);
stack.Push(4);
stack.PrintStack();
stack.Peek();
stack.Pop();
stack.PrintStack();
```

Output-
```
4
5
8
3
The top most element is 4
Popped the top most element
5
8
3
The length of the stack is 3
```

### Queue-

```
queue.Enqueue(1);
queue.Enqueue(6);
queue.Enqueue(9);
queue.Enqueue(4);
queue.PrintQueue();
queue.Peek();
queue.Dequeue();
queue.Dequeue();
queue.PrintQueue();
```

Output-
```
1
6
9
4
The length of the queue is 4
The top most element is 1
Removed an element
Removed an element
9
4
The length of the queue is 2
```

**Pull request merged**
