### PR TITLE
non duplicate array

### PR DESCRIPTION
**Pull request by Ttecs**
this program is not insert duplicate elements in to the array

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@Ttecs 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by hanshulll** [comment]
@Ttecs 
**Wohoo!! Congrats🥳 your PR has been merged.**

**Comment by hanshulll** [comment]
> this program is not insert duplicate elements in to the array

@Ttecs 
**Thank you so much for your contribution and if possible do provide a detailed description of what type of contribution you've done**

**Comment by Ttecs** [comment]
```
public static void main(String[] args) {
        NoDupArray x= new NoDupArray(6);
        x.insert(9);
        x.insert(9);
        x.insert(5);
        x.insert(5);
        x.insert(6);
        x.insert(9);
        x.insert(2);
        x.display();
       }
```
output is 

```
value allready exist
value allready exist
value allready exist
values in the array-----------
9 5 6 2 
```

it will only insert one unique number into the array 
        x.delete(5);
        x.display();
        x.insert(5);
        x.display();

output 
value allready exist
value allready exist
value allready exist
value deleted
values in the array-----------
9 6 2 
values in the array-----------
9 6 2 5

**Pull request merged**
