### PR TITLE
Added square of an integer without * operator (Java)

### PR DESCRIPTION
**Pull request by arjun-khanduri**
Hey @hanshulll!

I have added the Java code to __'Find the square of a number without using the multiplication operator or the pow function.'__

Please add the `hacktoberfest` tag if you merge the PR.

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]

**Comment by hanshulll** [comment]
@arjun-khanduri 
**Your PR has been successfully merged Thank you so much for your valuable contribution. Do give a follow if it helped you and star the repo and check other repo too for more contribution. Keep hacking**

**Comment by arjun-khanduri** [comment]
Thanks a lot @hanshulll :)

One question, am I allowed to contribute more to this repository?

**Comment by hanshulll** [comment]
@arjun-khanduri 
**I guess you can and also do check web-development repo try doing contribution their to looking forward to more contributions from you and don't forget to follow and gave a star to the repo if it was helpful 😅**

**Comment by arjun-khanduri** [comment]
Yes I'll do that, thank you :)

**Pull request merged**
