### PR TITLE
Added some DP Problems

### PR DESCRIPTION
**Pull request by sauravs0**
Dynamic Programming Problems List which I added -

01Knapsack.cpp
editDistance.cpp
longestIncreasingSubsequence.cpp
minCostPath.cpp
numOfBalancedBT.cpp
staircase.cpp
allPossibleWays.cpp
fibonacci.cpp
lootHouses.cpp
minCountofSquares.cpp
permutationCoefficient.cpp
coinChange.cpp
friendsPair.cpp
maximizeCutSegments.cpp
minStepsTo1.cpp
shortestSubsequence.cpp
coinTower.cpp
LCS.cpp
MCM.cpp
nthCatalanNumber.cpp
squareMatrixWithZeroes.cpp

Please let me know if you want some changes
Please merge this under the `Hacktoberfest` label!

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@sauravs0 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by hanshulll** [comment]
@sauravs0 
**Wohoo!! Congrarts🥳 your PR has been merged.**

**Comment by sauravs0** [comment]
image
@hanshulll It is showing that the project is not participating in `Hacktoberfest` on `Hacktoberfest` website

**Comment by hanshulll** [comment]
@sauravs0 
actually the project souravs0/Hactoberfest2021 is not participation !!

**Comment by sauravs0** [comment]
@hanshulll Thanks sir, Sorry to disturb you with such a little mistake, actually I'm new to Github :(

**Comment by hanshulll** [comment]
@sauravs0 
**No problem at all. keep hacking**

**Pull request merged**
