### PR TITLE
Create sortingarray.cpp

### PR DESCRIPTION
**Pull request by ankur12-1610**
Added sortingarray.cpp in C++ directory!

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@hanshulll please review the PR!

**Review by hanshulll — APPROVED** [review]

**Comment by hanshulll** [comment]
@ankur12-1610 
**Your PR has been successfully merged Thank you so much for your valuable contribution. Do give a follow if it helped you and star the repo and check other repo too for more contribution. Keep hacking**

**Comment by ankur12-1610** [comment]
A small request, can you please add labels to the PR.

Thank You

**Comment by hanshulll** [comment]
@ankur12-1610 
**Ohh no need to request it's my bad I forgot to label it in the first place so I apologize keep hacking**
**also don't forget to give a follow and star the repo if it was helpfull**

**Comment by ankur12-1610** [comment]
> @ankur12-1610 **Ohh no need to request it's my bad I forgot to label it in the first place so I apologize keep hacking** **also don't forget to give a follow and star the repo if it was helpfull**

Thank You!

**Pull request merged**
