### PR TITLE
Frequency of each element in the array

### PR DESCRIPTION
**Pull request by asknkitkr**

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@asknkitkr 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by hanshulll** [comment]
@asknkitkr 
**Wohoo!! Congrats🥳 your PR has been merged.**

**Comment by hanshulll** [comment]
> No description provided.

@asknkitkr 
**Thank you so much for your contribution and do provide a detailed description of what type of contribution you've done as soon as possible**

**Comment by asknkitkr** [comment]
Yeah sure

**Pull request merged**
