### PR TITLE
codechef problem in java

### PR DESCRIPTION
**Pull request by sumitchouhan13**

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@sumitchouhan13 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by sumitchouhan13** [comment]
Is my PR approved ?
and how many PR should I make to participate in Hacktoberfest 2021?

**Comment by hanshulll** [comment]
@sumitchouhan13 
**yeah your PR is approved and you have to do total 4 PR'S and don't forget to star this repo 😉. Keep hacking**

**Comment by krish-dev-7** [comment]
hey which problem should be solved?

**Comment by hanshulll** [comment]
@krish-dev-7 
**just add any working code it can be something which you are learning right now or you have practised some problem so add its code in the suitable directory**

**Comment by hanshulll** [comment]
@sumitchouhan13 
**Your PR has been successfully merged Thank you so much for your valuable contribution. Do give a star to the repo if it helped you and check other repo too for more contributions. Keep hacking**

**Pull request merged**
