### PR TITLE
thirdmaximumelementinarray.java

### PR DESCRIPTION
**Pull request by anisha16**
Code to find third maximum element in an array using java

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@anisha16 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by anisha16** [comment]
> @anisha16 **Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

Sure! Thanks :)

**Comment by hanshulll** [comment]
@anisha16 
**Wohoo!! Congrarts🥳 your PR has been merged.**

**Comment by anisha16** [comment]
> @anisha16 **Wohoo!! Congrarts🥳 your PR has been merged.**



> @anisha16 **Wohoo!! Congrarts🥳 your PR has been merged.**

Yay!! Thanks! :)

**Comment by anisha16** [comment]
> > @anisha16 **Wohoo!! Congrarts🥳 your PR has been merged.**
> 
> > @anisha16 **Wohoo!! Congrarts🥳 your PR has been merged.**
> 
> Yay!! Thanks! :)

Hey! Will this be accepted now? Heard that hacktoberfest is not accepting dsa repo anymore. Please confirm.

**Pull request merged**
