### PR TITLE
Bucket_Sort.cpp

### PR DESCRIPTION
**Pull request by Udyansingh**
I have created a BUCKET_SORTING algorithm in C++.

### CODE REVIEW

**Review by hanshulll — CHANGES_REQUESTED** [review]
@Udyansingh 
**Thank you so much for your contribution and do put your GitHub username either at the top or bottom of the code**

**Comment by Udyansingh** [comment]
Thankyou Sir, As you said I have mentioned my github username in the code.

**Comment by Udyansingh** [comment]
@hanshulll Please merge the PR #317

**Comment by hanshulll** [comment]
@Udyansingh 
**Actually this repo is now been excluded from hactoberfest I was fearing that it will happen eventually their can be any reason like a lot of spam PR’s so it can’t be helped but yeah it’s a one month long program so their is a lot of time to do more PR’s on many different repo’s. So, yeah Happy Hactoberfest**

**Pull request merged**
