### PR TITLE
added java method to generate hash code from any string

### PR DESCRIPTION
**Pull request by bpolaswar**

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@bpolaswar 
**can you modify it a little so that it can be understood easliy**

**Comment by hanshulll** [comment]
@bpolaswar 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by bpolaswar** [comment]
OK

**Comment by hanshulll** [comment]
@bpolaswar 
**Wohoo!! Congrarts🥳 your PR has been merged.**

**Pull request merged**
