### PR TITLE
Add : Dart Solutions

### PR DESCRIPTION
**Pull request by SushanShakya**

### CODE REVIEW

**Comment by hanshulll** [comment]
> No description provided.

@SushanShakya 
****Thank you so much for your contribution and do provide a detailed description of what type of contribution you've done**

**Comment by SushanShakya** [comment]
I have contributed solutions to famous problems from Exercism. Solutions along with tests.

**Comment by hanshulll** [comment]
> I have contributed solutions to famous problems from Exercism. Solutions along with tests.

@SushanShakya 
**Your PR will be merged soon but why you close it**

**Comment by SushanShakya** [comment]
I have updated and created a new pull request

**Pull request closed without merging**
