### PR TITLE
Palindrome.java added

### PR DESCRIPTION
**Pull request by RajdeepDs**

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@RajdeepDs 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by hanshulll** [comment]
@RajdeepDs 
**Your PR has been successfully merged Thank you so much for your valuable contribution. Do give a follow if it helped you and star the repo and check other repo too for more contribution. Keep hacking**

**Comment by RajdeepDs** [comment]
@hanshulll 
Thank You bro, I really appreciate your work.

**Comment by hanshulll** [comment]
@RajdeepDs 
**Feel free to check other repo too for more contributions looking forward to get more contributions from you keep hacking🙌🏻**

**Pull request merged**
