### PR TITLE
weather forecast by BajraYeJoon

### PR DESCRIPTION
**Pull request by BajraYeJoon**
# Weather Forecast Web Application ☁☁

### CODE REVIEW

**Comment by BajraYeJoon** [comment]
@hanshulll  Pull request has been done and the files are above in "weather forecast by BajraYeJoon" 
Please review it and merge for it to be accepted .😃😃

https://github.com/hanshulll/Hacktoberfest2021/pull/186/commits/e4fbea6e27b7c7061e485736d8d2036b3aa92d22

**Comment by hanshulll** [comment]
@BajraYeJoon 
**Don't worry it will be approved soon as you may know their are a lot PR's right now and also it's a one month program so don't worry it will be approved as soon as possible also I can't merge all PR's blindly as it may result in the repo being excluded from the program like many other repo so be patient full you PR will be accepted soon. Happy Hactoberfest**

**Comment by BajraYeJoon** [comment]
@hanshulll Apologies for incovenience. Will be waiiting for it to be merged. 😃😊

**Comment by hanshulll** [comment]
@BajraYeJoon 
**No problem at all, Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by BajraYeJoon** [comment]
@hanshulll  I have a doubt as I am new to hacktoberfest. this contribution is showing excluded project .Can you please explain what does it mean?🤔

**Comment by hanshulll** [comment]
@BajraYeJoon 
**Actually this repo is now been excluded from hactoberfest I was fearing that it will happen eventually their can be any reason like a lot of spam PR’s so it can’t be helped but yeah it’s a one month long program so their is a lot of time to do more PR’s on many different repo’s. So, yeah Happy Hactoberfest**

**Pull request merged**
