### PR TITLE
E-Mail Sender in Python

### PR DESCRIPTION
**Pull request by Karssido**

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@Karssido 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by hanshulll** [comment]
@Karssido 
**Wohoo!! Congrats🥳 your PR has been merged.**

**Comment by hanshulll** [comment]
> No description provided.

@Karssido 
**Thank you so much for your contribution and do provide a detailed description of what type of contribution you've done as soon as possible**

**Comment by Karssido** [comment]
It is showing excluded project on Hactoberfest site

**Comment by hanshulll** [comment]
@Karssido 
**Actually this repo is now been excluded from hactoberfest I was fearing that it will happen eventually their can be any reason like a lot of spam PR’s so it can’t be helped but yeah it’s a one month long program so their is a lot of time to do more PR’s on many different repo’s. So, yeah Happy Hactoberfest**

**Pull request merged**
