### PR TITLE
checking palindrome front and from back at X distance

### PR DESCRIPTION
**Pull request by Sharath-majjigi**
Hacktoberfest2021

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@Sharath-majjigi 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by Sharath-majjigi** [comment]
yes thankyou ! I have starred the repo ;)

**Comment by hanshulll** [comment]
@Sharath-majjigi 
**Wohoo!! Congrarts🥳 your PR has been merged.**

**Comment by hanshulll** [comment]
@Sharath-majjigi 
**don't forget to star the repo 🥳**

**Comment by Sharath-majjigi** [comment]
Thankyou ☺️ but it didnt get updated !

**Comment by hanshulll** [comment]
@Sharath-majjigi  
**just refresh it or wait for some time there is a server issue it will definitely gonna update so don't worry.**

**Pull request merged**
