### PR TITLE
Added Façade design pattern

### PR DESCRIPTION
**Pull request by Deshan-Chathuranga**

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@Deshan-Chathuranga 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by hanshulll** [comment]
@Deshan-Chathuranga 
**Your PR has been successfully merged Thank you so much for your valuable contribution. Do give a star to the repo if it helped you and check other repo too for more contributions. Keep hacking**

**Comment by Deshan-Chathuranga** [comment]
Thank You!!

**Comment by hanshulll** [comment]
@Deshan-Chathuranga 
**no problem at all and don't forget to star the repo 😉!!**

**Comment by Deshan-Chathuranga** [comment]
Alredy done bro.

**Pull request merged**
