### PR TITLE
Added a JS project (A simple two player dice game).

### PR DESCRIPTION
**Pull request by DeepakYadav01**
It is a two player dice rolling game, which is build using HTML, CSS and JavaScript.

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@DeepakYadav01 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by hanshulll** [comment]
@DeepakYadav01 
**Wohoo!! Congrats🥳 your PR has been merged.**

**Comment by DeepakYadav01** [comment]
@hanshulll 
Thanks bro,
and  please check my one more PR i.e a java code check linkedlist palindrome and merge that as well.

**Comment by hanshulll** [comment]
@DeepakYadav01 
**Thank you so much for your contribution and if possible do provide a detailed description of what type of contribution you've done**

> @hanshulll
> Thanks bro,
> and please check my one more PR i.e a java code check linkedlist palindrome and merge that as well.

**Thank you so much for your contribution and if possible do provide a detailed description of what type of contribution you've done on that PR**

**Pull request merged**
